version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - WAIT_VERSION=2.7.3
        - WAIT_HOSTS=${DB_HOST}:5432
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/server
    env_file:
      - ./.env

  database:
    image: postgres:12.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - ./.env

volumes:
  pgdata:
    driver: local
